version: '3.8'

services:
  interver_api:
    build: .
    image: interver
    container_name: api-container
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
      SQLALCHEMY_DATABASE_URL_ASYNC: ${{ secrets.SQLALCHEMY_DATABASE_URL_ASYNC }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
