apiVersion: apps/v1
kind: Deployment
metadata:
  name: interver
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 900478210705.dkr.ecr.ap-northeast-2.amazonaws.com/interver:55179916263211f6836ba71ba27330807b58c8ac
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: interver-app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
