"""empty message

Revision ID: 5fcb0b395eef
Revises: 8d0e82e59937
Create Date: 2024-03-28 18:46:05.771957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcb0b395eef'
down_revision: Union[str, None] = '8d0e82e59937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'rating')
    # ### end Alembic commands ###
