"""empty message

Revision ID: 6a0bbd616f5f
Revises: 85272993ba86
Create Date: 2024-04-02 14:40:16.084732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0bbd616f5f'
down_revision: Union[str, None] = '85272993ba86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_voter')
    op.drop_table('question_voter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_voter',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_question_voter_question_id_question'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_voter_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name='pk_question_voter')
    )
    op.create_table('answer_voter',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_voter_answer_id_answer'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_voter_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name='pk_answer_voter')
    )
    # ### end Alembic commands ###
